---
- name: install-prerequisite
  hosts: all

  roles:
    - role: 1-install-prerequisite

  gather_facts: true
  any_errors_fatal: yes

- name: Install Container(Docker or Containerd)
  hosts: all

  roles:
    - role: 2-install-container 

- name: Install kubelet, kubectl, kubeadm, kube-cni
  hosts: all

  roles:
    - role: 3-install-kube

- name: kubeadm init & join
  hosts: all

  roles:
    - role: 4-kube-init-join

- name: install cni
  hosts: master

  roles:
    - role: 5-install-cni

- name: install Ingress Controller
  hosts: master

  roles:
    - role: 6-install-ingress

