---
- name: Template config.yaml
  template:
    src: config.yaml.j2
    dest: /var/lib/kubelet/config.yaml

- name: Template kubeadm-flags.env
  template:
    src: kubeadm-flags.env.j2
    dest: /var/lib/kubelet/kubeadm-flags.env

#- name: Template kubelet
#  template:
#    src: kubelet.j2
#    dest: /etc/sysconfig/kubelet

- name: Reload changing kubelet
  command: systemctl daemon-reload

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - kubelet
