---
- wait_for:
    host: 127.0.0.1
    port: "{{ kube_apiserver_port }}"
    delay: 10

- name: Copy coredns_configmap.sh
  copy:
    src: coredns_configmap.sh
    dest: "{{ kube_addon_dir }}/coredns_configmap.sh"

- name: "Mode 755 for coredns_configmap.sh"
  file:
    path: "{{ kube_addon_dir }}/coredns_configmap.sh"
    mode: 0755

- name: Run coredns_configmap.sh
  shell: >
    /bin/sh -c "{{ kube_addon_dir }}/coredns_configmap.sh"
